# Generated by Django 4.2.6 on 2023-10-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='team',
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.ManyToManyField(to='team_person.team'),
        ),
    ]
